name: Deploy
on: [push, pull_request, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TARGET: static 
      DEV_NO_AUTH: true
      BASE_PATH: /fff-support-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Generate static files
        run: npm run generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist